/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.salarymanagement;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author parma
 */
public class GiveSalaryShare extends javax.swing.JFrame {
    SalaryData sdata;
    Validations validity = new Validations();
    EmployeeClass data;
    ConnectionClass connectionClass = ConnectionClass.getInstance();
    int isUpdate=0;

    /**
     * Creates new form ManageSalary
     */
    public GiveSalaryShare() {
        try {
            initComponents();
            consultant.setVisible(false);
            share1.setVisible(false);
            String query = "SELECT name from users WHERE role=2";
            PreparedStatement ps = connectionClass.connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            consultants.removeAllItems();
            consultants.addItem("<<  Select consultant  >>");
            while (rs.next()) {
                consultants.addItem(rs.getString("name"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(GiveSalaryShare.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public GiveSalaryShare(EmployeeClass data) {
        try {

            initComponents();
            this.data = data;
            consultant.setVisible(false);
            share1.setVisible(false);
            date.setText(validity.currentDate());
            data.getId();
            data.getName();
            data.getEmail();
            data.getAddress();
            data.getContact();
            data.getAge();
            data.getPass();
            data.getJoining();
            data.getRole();
            date.setEditable(false);
            id.setEditable(false);
            String query = "SELECT name from users WHERE role=?";
            PreparedStatement ps = connectionClass.connection.prepareStatement(query);
            int role = 2;
            ps.setInt(1, role);
            ResultSet rs = ps.executeQuery();
            consultants.removeAllItems();
            consultants.addItem("<<  Select consultant  >>");
            while (rs.next()) {
                consultants.addItem(rs.getString("name"));
            }

        } catch (SQLException ex) {
            Logger.getLogger(GiveSalaryShare.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public GiveSalaryShare(SalaryData sdata, EmployeeClass data) {
        try {

            initComponents();
            isUpdate++;
            this.data = data;
            consultant.setVisible(false);
            share1.setVisible(false);
            date.setText(validity.currentDate());
            data.getId();
            data.getName();
            data.getEmail();
            data.getAddress();
            data.getContact();
            data.getAge();
            data.getPass();
            data.getJoining();
            data.getRole();
            date.setEditable(false);
            id.setEditable(false);
            String query = "SELECT name from users WHERE role=?";
            PreparedStatement ps = connectionClass.connection.prepareStatement(query);
            int role = 2;
            ps.setInt(1, role);
            ResultSet rs = ps.executeQuery();
            consultants.removeAllItems();
            consultants.addItem("<<  Select consultant  >>");
            while (rs.next()) {
                consultants.addItem(rs.getString("name"));
            }

        } catch (SQLException ex) {
            Logger.getLogger(GiveSalaryShare.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.sdata=sdata;
        consultants.setSelectedItem(sdata.getConsultantName());
        id.setText(String.valueOf(sdata.getConsultantId()));
        salary.setText(String.valueOf(sdata.getSalary()));
        date.setText(sdata.getDate());
        sdata.getManagerId();
        sdata.getId();
        heading.setText("Update Salary");
        btn.setText("Update Salary");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        consultants = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        share1 = new javax.swing.JLabel();
        consultant = new javax.swing.JLabel();
        btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        heading.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("Give Salary");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Consultant ID");

        consultants.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        consultants.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultantsMouseClicked(evt);
            }
        });
        consultants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultantsActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Salary Share");

        salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryActionPerformed(evt);
            }
        });
        salary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                salaryKeyTyped(evt);
            }
        });

        share1.setForeground(new java.awt.Color(255, 0, 0));
        share1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        share1.setText("Error");

        consultant.setForeground(new java.awt.Color(255, 0, 0));
        consultant.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        consultant.setText("Error");

        btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn.setText("Give Salary");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Select Consultant");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Date");

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Return Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(consultants, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(salary, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                            .addComponent(share1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(consultant, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultants, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultant)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salary, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(share1)
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(833, 541));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryActionPerformed

    private void salaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salaryKeyTyped
        // TODO add your handling code here:
        validity.isValidNumber(evt, share1);
    }//GEN-LAST:event_salaryKeyTyped

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:
        if (consultants.getSelectedIndex() == 0) {
            consultant.setText(" !! Select Consultant name");
            consultant.setVisible(true);
        } else if (salary.getText().isEmpty()) {
            share1.setText("Enter Salary share!!");
            share1.setVisible(true);
        } else if(isUpdate ==0) {
            String query = "INSERT INTO MANAGE_SALARY(ManagerID,"
                    + "consultantName,"
                    + "consultantID,"
                    + "Date,"
                    + "SalaryShare) "
                    + "VALUES(?,?,?,?,?)";
            PreparedStatement ps = null;
            try {
                ps = connectionClass.connection.prepareStatement(query);

                ps.setInt(1, data.getId());
                ps.setString(2, name);
                ps.setInt(3, consultantID);
                ps.setString(4, date.getText());
                ps.setDouble(5, Double.parseDouble(salary.getText()));
                ps.execute();
                JOptionPane.showMessageDialog(null, "Salary share of " + Double.parseDouble(salary.getText()) + " given to " + name + " successfully");
                ManagerHome home = new ManagerHome(data);
                home.setVisible(true);
                this.dispose();

            } catch (SQLException ex) {
                Logger.getLogger(AddConsultant.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(AddConsultant.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(isUpdate!=0){
            String query = "UPDATE MANAGE_SALARY set ManagerID=?, consultantName=?, consultantID=?, Date=?, SalaryShare=? WHERE ID=?";
            PreparedStatement ps = null;
            try {
                ps = connectionClass.connection.prepareStatement(query);

                ps.setInt(1, data.getId());
                ps.setString(2, name);
                ps.setInt(3, consultantID);
                ps.setString(4, date.getText());
                ps.setDouble(5, Double.parseDouble(salary.getText()));
                ps.execute();
                JOptionPane.showMessageDialog(null, "Salary share of " + Double.parseDouble(salary.getText()) + " given to " + name + "  updated successfully");
                ManagerHome home = new ManagerHome(data);
                home.setVisible(true);
                this.dispose();

            } catch (SQLException ex) {
                Logger.getLogger(AddConsultant.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(AddConsultant.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnActionPerformed
    String name;
    int consultantID;
    private void consultantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultantsActionPerformed
        try {
            // TODO add your handling code here:
            name = (String) consultants.getSelectedItem();
            if (consultants.getSelectedIndex() != 0) {
                String query = "SELECT ID from users where name=? AND role=?";
                int role = 2;
                PreparedStatement ps = connectionClass.connection.prepareStatement(query);
                ps.setString(1, name);
                ps.setInt(2, role);
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    id.setText(String.valueOf(rs.getInt("ID")));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(GiveSalaryShare.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_consultantsActionPerformed

    private void consultantsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultantsMouseClicked
        // TODO add your handling code here:
        consultant.setVisible(false);
    }//GEN-LAST:event_consultantsMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            ManagerHome home=new ManagerHome(data);
            home.setVisible(true);
            this.dispose();
        } catch (ParseException ex) {
            Logger.getLogger(GiveSalaryShare.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GiveSalaryShare.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiveSalaryShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiveSalaryShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiveSalaryShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiveSalaryShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiveSalaryShare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JLabel consultant;
    private javax.swing.JComboBox<String> consultants;
    private javax.swing.JTextField date;
    private javax.swing.JLabel heading;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField salary;
    private javax.swing.JLabel share1;
    // End of variables declaration//GEN-END:variables
}
